services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - database
    cpus: 0.5
    mem_limit: 260
    env_file:
      - .env

  database:
    image: postgres
    cpus: 0.35
    mem_limit: 212
    env_file:
      - .env