version: '2.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - database
    cpus: 2
    mem_limit: 2G
    env_file:
      - .env

  database:
    image: postgres
    cpus: 2
    mem_limit: 2G
    env_file:
      - .env